# Generated by Django 6.0.2 on 2026-02-26 07:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_location', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('estimated_arrival', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In-Transit', 'In-Transit'), ('Completed', 'Completed'), ('Alert', 'Alert')], default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('truck_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('driver_name', models.CharField(max_length=255)),
                ('cargo_type', models.CharField(max_length=255)),
                ('cargo_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GPSLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_logs', to='surveillance.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('alert_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Vision', 'Vision Detection'), ('Behavior', 'Suspicious Behavior'), ('Route', 'Route Deviation'), ('System', 'System Alert'), ('Fusion', 'High Risk Fusion Alert')], max_length=20)),
                ('risk_score', models.FloatField()),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='surveillance.trip')),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='surveillance.truck'),
        ),
    ]
