# Generated by Django 6.0.2 on 2026-02-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='destination',
            new_name='destination_name',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='start_location',
            new_name='start_location_name',
        ),
        migrations.RemoveField(
            model_name='gpslog',
            name='speed',
        ),
        migrations.AddField(
            model_name='alert',
            name='ai_explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20),
        ),
        migrations.AddField(
            model_name='gpslog',
            name='door_sealed',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='gpslog',
            name='engine_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gpslog',
            name='heading',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='gpslog',
            name='speed_kmh',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trip',
            name='baseline_route_risk',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trip',
            name='current_calculated_risk',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trip',
            name='destination_coords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_location_coords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='driver_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='iot_sensor_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='license_plate',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='vehicle_make_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('Vision', 'Vision Detection'), ('Behavior', 'Suspicious Behavior'), ('Route', 'Route Deviation'), ('System', 'System Alert'), ('Fusion', 'High Risk Fusion Alert'), ('IoT', 'IoT Sensor Anomaly')], max_length=20),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('In-Transit', 'In-Transit'), ('Completed', 'Completed'), ('Alert', 'Alert'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20),
        ),
    ]
