# Generated by Django 6.0.2 on 2026-02-26 10:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0002_rename_destination_trip_destination_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsCompany',
            fields=[
                ('company_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(default='India', max_length=100)),
                ('website', models.URLField(blank=True, null=True)),
                ('control_email', models.EmailField(blank=True, help_text='Main control room email', max_length=254, null=True)),
                ('control_phone', models.CharField(blank=True, help_text='Main control room phone (Twilio SMS)', max_length=20, null=True)),
                ('active', models.BooleanField(default=True)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Logistics Company',
                'verbose_name_plural': 'Logistics Companies',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='gpslog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['-start_time']},
        ),
        migrations.AlterModelOptions(
            name='truck',
            options={'ordering': ['license_plate']},
        ),
        migrations.AddField(
            model_name='alert',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='sms_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='truck',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='truck',
            name='driver_email',
            field=models.EmailField(blank=True, help_text='Driver email for alert notifications', max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='ControlAreaContact',
            fields=[
                ('contact_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, help_text='e.g. Fleet Manager, Security Officer', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('notify_email', models.BooleanField(default=True)),
                ('notify_sms', models.BooleanField(default=True)),
                ('min_severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='surveillance.logisticscompany')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='truck',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trucks', to='surveillance.logisticscompany'),
        ),
    ]
